ethereum/lahja

examples/request_api.py
lahja/endpoint.py
lahja/eventbus.py
tests/core/conftest.py
tests/core/test_basics.py

Since it seems we won't add `CancelToken` support as proposed in #9, here are a couple of things that I extracted from that PR:
- A fix were we tried to propagate events when the event bus was already shut down
- fixed broken example
- tightened tests and assertions
- basic cleanup
:fire:

Some minor fixes and cleanup

---

lahja/endpoint.py
lahja/misc.py
tests/core/conftest.py
tests/core/test_internal.py

As described in #10. Currently the event bus always propagates every event at least one process hop to the process that holds the central `EventBus` to then decide whether to pass it on to a specific `Endpoint` or not.
Not only is this a waste of resources for events that do not need to propagate outside of the current `Endpoint` it will also prevent us from propagating non-pickable events in such cases.
Added `internal` to the `BroadcastConfig` and then decide based on that to either propagate externally or just internally.

Implement internal events

---

tests/core/test_basics.py

We didn't have a test case that demoes how an `AsyncGenerator` returned from `stream()` is automatically cancelled when the parent `task` was cancelled.
Added test case

Add another test case

---

examples/inter_process_ping_pong.py
examples/request_api.py
lahja/endpoint.py
tests/core/conftest.py
tests/core/test_basics.py

As described in #17 internal events do not work with non-pickable events as is (but should)
First off, apologies that this turned into some re-architecture that is now mangled in a single commit and hard to detangle. As I was fixing the core problem - which is that internal events need to be propagate through their own special purpose queue - I stumbled over a bunch of problems that needed to be addressed. 
So here is what this does in a nutshell:
- use an `asyncio.Queue` to propagate internal events
- simplify the `def connect()` logic and rename to `def connect_no_wait()`
- add an `async def wait_for_connection()` API that allows async waiting up to the point where the background processing loops have started their work. This fixing an important problem that existed to far which was …

Ensure internal events work with non-pickable events

---

.circleci/config.yml
lahja/tools/benchmark/__init__.py
lahja/tools/benchmark/constants.py
lahja/tools/benchmark/process.py
lahja/tools/benchmark/stats.py
lahja/tools/benchmark/typing.py
lahja/tools/benchmark/utils/reporting.py
scripts/perf_benchmark.py
tox.ini

We currently do not have benchmarks, which means we don't really know how well the event bus scales under load.
We'd like to get various metrics for different scenarios e.g.
- pushing `n` number of events to `m` processes
- same as above but with different size of payload
- ...
Adds some basic benchmarks. Still incomplete and not not polished.

Add benchmarks

---

lahja/endpoint.py

When a stream is cancelled the exception is re-raised. I don't recall why I did that or if it was just a left over but it causes these problems in Trinity.
```
WARNING  12-07 20:34:23      DiscoveryService  Task <coroutine object DiscoveryService.handle_get_random_bootnode_requests at 0x7f45ad668150> finished unexpectedly: 
DEBUG  12-07 20:34:23      DiscoveryService  Task failure traceback
Traceback (most recent call last):
File "/home/cburgdorf/Documents/hacking/ef/py-evm/p2p/service.py", line 141, in _run_task_wrapper
await awaitable
File "/home/cburgdorf/Documents/hacking/ef/py-evm/p2p/service.py", line 160, in _run_daemon_task_wrapper
await awaitable
File "/home/cburgdorf/Documents/hacking/ef/py-evm/trinity/plugins/builtin/peer_discovery/discovery_service.py", line 70, in …
```

Do not reraise cancellations

---

setup.py

Builds started failing because `pytest-xdist` (which wasn't pinned) started expecting a higher pytest version.
Upgraded all pytest libs to their latest versions.

Upgrade pytest libs

---

lahja/endpoint.py

Currently, it seems it may happen that we run into a situation where we try to resolve a future that was already cancelled. Similarly it could *theoretically* happen that we try to set a result on a future that is already done.
This may be a fix for https://github.com/ethereum/py-evm/issues/1613
Check if the future is already done or cancelled before setting the result.

Do not set results on futures that are cancelled or done

---

examples/inter_process_ping_pong.py
examples/request_api.py
lahja/endpoint.py
lahja/tools/benchmark/process.py
lahja/tools/benchmark/stats.py
scripts/perf_benchmark.py
tests/core/conftest.py
tests/core/helpers.py
tests/core/test_basics.py
tests/core/test_connect.py
tests/core/test_internal.py
tests/core/test_stop.py

While working on #39 I attempted to make `Endpoint.broadcast()` async. That PR uses asyncio to communicate with other Endpoints, so any caller attempting to `broadcast()` must either be a coroutine which is okay with being blocked or call `asyncio.ensure_future`.
This PR makes some interface changes:
- `Endpoint.broadcast()` is now async
- `Endpoint.broadcast_nowait()` now exists and does what `Endpoint.broadcast()` used to do.
- `start_serving_nowait()` no longer exists. Callers must use `Endpoint.start_serving()`.
- `start_serving()` no longer accepts an event loop, it uses the current event loop.
I don't believe that this PR meaningfully changes behavior, but Christoph pointed out that #39, the reason for this PR, will block calling coroutines if other processes manage to block their …

Make Endpoint.broadcast() async

---

.bumpversion.cfg
docs/release_notes.rst
setup.py

A new lahja version needs to be released for https://github.com/ethereum/trinity/pull/556 to be mergable. 
Here are some candidate release notes. I think that I've done everything I can do from [this list](https://github.com/ethereum/snake-charmers-tactical-manual/blob/master/cutting-a-release.md) without access to pypi. Do these release notes look good? How should I go about getting access to pypi & readthedocs?

Release 0.12.0

---

lahja/_snappy.py
lahja/endpoint.py

Snappy support check should be re-usable.  
Moved it to a private namespace and made it easy to import without having to do error checking every place we want to check.

Simplify snappy support check

---

lahja/__init__.py
lahja/endpoint.py
lahja/tools/benchmark/__init__.py
lahja/tools/benchmark/process.py
setup.py
tests/core/conftest.py
tests/core/helpers.py
tests/core/test_basics.py
tests/core/test_broadcast_config.py
tests/core/test_connect.py
tests/core/test_import.py
tests/core/test_internal.py
tests/core/test_stop.py
tests/mypy_typing_test.py
tox.ini

fixes #52 
`trio` specifies `mypy` as a dependency and it requires a newer version than `lahja` uses.
Updated `mypy` to latest and fixed type hints.  Also went ahead and addressed #52

Remove type hints from tests

---

lahja/endpoint.py

The `Endpoint.run` method should set the event loop on the endpoint upon entry.
Check if the `self._loop` is unset and set it if it is.

Set event loop in Endpoint.run if not already set

---

setup.py

The `setup.py` file format caused linting errors in my editor.
Changed from using line broken list addition to use `list.extend` to build the `[dev]` install requirements.

setup.py linting cleanup

---

lahja/asyncio/endpoint.py

Some simple performance gains to be reaped.
Removed the assert statements and combined the socket sending to be a single send.
Benchmarked as being about 17% faster.  The majority of this comes from reducing the number of socket sends with a small independent boost coming from removal of the `assert/isinstance` check.
Benchmarked using:
```
$ python ./scripts/perf_benchmark.py --num-processes 10 --num-events 10000
```
```
+++ASYNCIO+++
+++Globals+++
|Consumer processes |   Total time   | Total aggegated time  | Propagated events  |Received events | Propagated EPS |  Received EPS  |
|        10         |    2.74184     |       24.27840        |       10000        |     100000     |    3647.186    |   36471.863    |
+++Process Details+++
|      Process      |Processed Events|   First sent …
```

Simple performance improvements

---

.circleci/config.yml
setup.py
tox.ini

`pytest-asyncio` does not play nicely with other asyncio frameworks as it tries to run **any** fixture that is a coroutine which causes `trio` based fixtures to error.
Namespace and isolate the `asyncio` tests.

Namespace and isolate the asyncio tests in tox

---

lahja/asyncio/endpoint.py
lahja/common.py

The use of `TRANSPARENT_EVENT` was a legacy carry-over from the multiprocessing days.  It isn't needed anymore.
Removed it.

Remove TRANSPARENT_EVENT

---

lahja/asyncio/endpoint.py
lahja/base.py
lahja/common.py

As I started working on getting the `trio` endpoint up-to-speed with the latest changes it became apparent that there will be at lest some minimal re-usability needed between the concepts the endpoints use like the `InboundConnection` and `OutboundConnection`, primarily in the way that they interact with subscriptions.
Also, there were still some constructs living in `lahja.asyncio.endpoint` that belonged in `lahja.common`
Wrote a simple `ABC` base class for the `Connection` API.

Standardize internal connection API

---

lahja/asyncio/endpoint.py
tests/core/asyncio/test_connect.py

The `Endpoint.connect_to_endpoint` API was not checking for an existing connection.
Added the check and updated test to exercise that code path.

Error check in main connect_to_endpoint API

---

lahja/asyncio/endpoint.py

The `OutboundConnection` object's `can_send_item` method checked *up-to* three things to determine if sending was valid.  The current implementation computed all three of these conditions and then iterated them in precedence order to determine the result.
This is sub-optimal because in cases where the function returns because of the highest precedence check, the lower precedence checks are not used.
Adjust the function such that it only computes the minimal data it needs.

optimize can_send_item a little

---

docs/api.rst
lahja/base.py

fixes #64
It turns out that `Endpoint.broadcast_nowait` is likely necessary.  Without it you simply cannot talk to the event bus from APIs that are synchronous.
No core change other than adding it to the core API definition.
> I plan to majorly expand the test suite soon but only after I get the reverse server -> client connection stuff in because it improves the testing experience significantly

Add broadcast_nowait to core API

---

lahja/asyncio/endpoint.py
lahja/common.py
lahja/exceptions.py

Both the `broadcast` and `request` methods were setting private attributes of the `BaseEvent`
Added `BaseEvent.bind` API to deal with these and internal `_broadcast` implementation that does the binding in a common location.

BaseEvent.bind API

---

tests/core/asyncio/conftest.py

The `function` scope is the default scope for fixtures and was used redundantly.
Dropped it from all fixtures

Drop explicit scope from fixture

---

lahja/asyncio/endpoint.py
lahja/base.py
tests/core/asyncio/test_asyncio_subscriptions_api.py
tests/core/asyncio/test_basics.py
tests/core/asyncio/test_broadcast_config.py

fixes #65 
The `EndpointAPI.subscribe` API was defined as synchronous, but has an internal need to perform an asynchronous action to update the endpoint subscriptions.
Updated the API to be async as well as expanding the API to allow the *handler* to be a coroutine.

Update `EndpointAPI.subscribe` to be async and to accept coroutines

---

docs/api.rst
lahja/asyncio/endpoint.py
lahja/base.py
tests/core/asyncio/test_asyncio_subscriptions_api.py
tests/core/asyncio/test_basics.py
tests/core/asyncio/test_broadcast_config.py

built on top of #70 
The concept op remote connections is currently divide across two classes.  One for *inbound* and one for *outbound*.  The reality is these connections are bi-directional, we just don't take advantage of this.
It is currently not intuitive that if I do `client.connect_to_endpoint(server)` and then `server.broadcast()` that the client will not receive the broadcast.
For connections that need to talk both ways, leveraging both directions of the connection should reduce the number of sockets and connections we need to make.
In the upcoming `trio` implementation in #56 there is an API that leverages the bi-directional nature of connections to make `server.broadcast()` send things back to clients that are connected.
This PR is a prerequisite to that functionality, …

Combine inbound and outbound connection concepts

---

lahja/asyncio/endpoint.py
lahja/base.py
lahja/common.py
lahja/tools/benchmark/process.py
tests/core/asyncio/test_asyncio_subscriptions_api.py
tests/core/asyncio/test_basics.py
tests/core/asyncio/test_broadcast_config.py
tests/core/asyncio/test_internal.py
tests/core/asyncio/test_subscription_wait_apis.py

The current APIs that let one wait on remote subscriptions aren't flexible enough and aren't generalized enough to be shared across the `TrioEndpoint`
See previous discussion: https://github.com/ethereum/lahja/pull/72#issuecomment-494425741
1. Every specific endpoint has to implement the following API
```python
@abstractmethod
def get_connected_endpoints_and_subscriptions(
self
) -> Tuple[Tuple[str, Set[Type[BaseEvent]]], ...]:
"""
Return all connected endpoints and their event type subscriptions to this endpoint.
"""
pass
```
@pipermerriam This is where this PR diverges from your proposal because I *think* this single API should be enough. If a connected remote endpoint does not hold event subscriptions it will still be listed here with an empty set. So, I don't think we need to have a …

More flexible wait APIs

---

lahja/asyncio/endpoint.py
lahja/base.py
lahja/common.py
lahja/tools/benchmark/process.py
lahja/tools/benchmark/typing.py
lahja/typing.py
scripts/perf_benchmark.py
tox.ini

Builds on #99 
The cost of generating a UUID is *maybe* more expensive.
Custom scheme that *might* have minimal overhead.

Stop using uuid for request_id

---

lahja/__init__.py
lahja/base.py

The `BaseEndpoint` API isn't properly represented on the `EndpointAPI` meaning that 3rd party libraries that generically specify `EndpointAPI ` as an object type will get type checking errors if they use any of the subscription methods.
Added all of them as `abstractmethod`.

Ensure full API is represented on EndpointAPI

---

lahja/asyncio/endpoint.py
lahja/base.py
lahja/common.py
tests/core/asyncio/test_asyncio_subscriptions_api.py
tests/core/asyncio/test_base_wait_connections_changed_api.py
tests/core/asyncio/test_base_wait_until_any_remote_subscriptions_changed_api.py
tests/core/asyncio/test_connect.py

Builds from #107 
I didn't like that the generic implemetnations of the various subscription based `wait` APIs prescribed implementation details, primarily, that each implementation was required to implement something that streamed an event over the local bus to signal the change.
We also need an api for waiting until a connection is established to a specific endpoint.
Now there are two methods that each endpoint must implement:
- `wait_until_remote_subscriptions_change`
- `wait_until_connections_change`
From these two APIs, all of the following can be constructed generically in the `BaseEndpoint` class.
- `wait_until_connections_change`
- `wait_until_connected_to` (new API)
- `wait_until_remote_subscriptions_change`
- `are_all_remotes_subscribed_to`
- …

Generic wait for subscriptions and connection change

---

lahja/asyncio/endpoint.py
lahja/base.py

Builds from #108 
Fixes #109 
The manner in which subscription updates were issued had two issues that could be improved.
1. Multiple quick updates to the local subscription API would result in multiple updates being sent, when really only the last update is relevant.
2. The API was only callable from async contexts, requiring the use of `asyncio.ensure_future` when updates occur from a sync context.
Use an `asyncio.Event` that is cycled out each time it's triggered, allowing multiple call sites to call `Event.set()` but only trigger a single update.  This has the bonus benefit of not requiring an async context since `Event.set` is synchronous.

Cleanup local api for sending subscription updates to remotes

---

lahja/asyncio/endpoint.py
lahja/tools/benchmark/process.py
tests/core/asyncio/test_asyncio_subscriptions_api.py

I ditched a branch but it had some cleanups I wanted to maintain that are a bit random.
Combined them into this single PR.
- `__str__` and `__repr__` methods for `RemoteEndpoint`
- some code comments
- a minor bugfix in the resource locking of `RemoteEndpoint.subscribed_messages`
- `__str__` and `__repr__` methods for `AsyncioEndpoint`
- Nicer killing of the main driver process in the benchmarks.
- Wait until later to block on subscription in the benchmark reporter process
- A pre-assertion for a test

Misc cleanups

---

examples/inter_process_ping_pong.py
lahja/asyncio/endpoint.py
lahja/base.py
tests/core/asyncio/test_asyncio_subscriptions_api.py
tests/core/asyncio/test_base_wait_until_any_remote_subscriptions_changed_api.py
tests/core/asyncio/test_basics.py
tests/core/asyncio/test_broadcast_config.py
tests/core/asyncio/test_subscription_wait_apis.py

This is an alternative to #105 that makes the `subscribe` API synchronous. The only reason **not to do this** that I'm aware of would be that the `TrioEndpoint` may not be able to have a synchronous `subscribe`?
Nothing changes about it's implementation. Just dropping the `async` in the function definition.

Make subscribe API non-async

---

lahja/asyncio/endpoint.py
lahja/base.py
lahja/typing.py

As we move towards multiple implementations of the endpoint concept, the more logic we can de-duplicate the better (mostly).  One thing limiting this is the framework specific `Event/Condition/Lock` classes.  As it turns out, these have the same API signature in both `asyncio` and `trio`.
We need a common way to define these standard APIs so that common non-framework specific business logic can move into base classes.  Part of this is a common definition of the shape of a `RemoteEndpoint`
Implemented `BaseEndpointAPI` which defines the basics for interacting with a remote endpoint connection.
This includes `ABC` base classes for the `Lock/Condition/Event` APIs (though it requires a little coercion to get mypy to like it.)

Abstract base API for RemoteEndpoint

---

lahja/asyncio/endpoint.py
lahja/base.py
tests/core/asyncio/test_asyncio_subscriptions_api.py
tests/core/asyncio/test_basics.py

I could never remember which class used `subscribed_messages` and which used `subscribed_events`
Changed them to use the same variable name.

Rename subscribed_messages to subscribed_events

---

lahja/asyncio/endpoint.py
lahja/base.py
lahja/common.py
tests/core/asyncio/conftest.py
tests/core/asyncio/test_connect.py
tests/core/asyncio/test_endpoint_local_broadcast.py

We need the ability for an endpoint to consume events from itself (as if it were connected).
This is a *partial* fix since it's unclear what to do about the varios `wait_until` and `is_connected` APIs.
This ensures that all of the primary event base APIs on an endpoint work as expected for local consumption of events.

Ensure local use of endpoint works

---

examples/inter_process_ping_pong.py
examples/request_api.py
lahja/asyncio/endpoint.py
lahja/base.py
lahja/tools/benchmark/process.py
tests/core/asyncio/test_asyncio_subscriptions_api.py
tests/core/asyncio/test_base_wait_until_any_remote_subscriptions_changed_api.py
tests/core/asyncio/test_basics.py
tests/core/asyncio/test_broadcast_config.py
tests/core/asyncio/test_endpoint_local_broadcast.py
tests/core/asyncio/test_internal.py

I got in a hurry and didn't take into account that this needed to be sorted out.
The various APIs for *waiting* on subscriptions, checking subscriptions, waiting on connections and checking connections don't always behave in intuitive ways when dealing with a singular endpoint as if it was two endpoints which is a feature that we want to support.
Endpoints now treat themselves as a connected endpoint.  All of the various *wait* APIs will treat *self* as part of the set of connected endpoints.
This also results in renaming some of the APIs that previously used the term *remote* to instead use *endpoint* since it is inconsistent to refer to ourselves as a remote.
The only exception is the `wait_until_all_endpoints_subscribed` and `are_all_endgoints_subscribed` which each take an optional …

Self subscribe API with auto-opt-in

---

lahja/base.py
tests/core/asyncio/test_asyncio_subscriptions_api.py
tests/core/asyncio/test_broadcast_config.py

Negative bool flags lead to double negative checks
that are more error prone, like: `if not exclude_self`
Changed `exclude_self` param that defaulted to `False` to `include_self` param that defaults to `True`.

Change `exclude_self` parm to `include_self`

---

.gitignore

The `.pytest_cache` directory was not on the `gitignore` file.
Added it

Ignore .pytest_cache directory

---

lahja/asyncio/endpoint.py

Two places used `Exception` where `ConnectionAttemptRejected` would probably be more appropriate. Also the Exception message had a `TODO` in it.
- use `ConnectionAttemptRejected` type
- get rid of todo in exception message

Use proper exception classes

---

README.md
setup.py

The description on pipy could not handle the markdown syntax
1. Manually handling the description in the same way we do for Trinity
2. Minor tweaks in the readme itself

Fix long description on pipy

---

lahja/asyncio/endpoint.py
lahja/base.py
lahja/tools/benchmark/process.py

Builds on #130 
The mechanisms for starting a background process in `trio` vs `asyncio` are not compatible.  In `trio`, our `start` methods have to be passed a nursery object in order for them to be capable of starting things up and then returning.
The `BaseEndpointAPI` defined a `start` method which results in the base implementation not being compatible with what we need for the trio implementation to fit within the model.
Converted it to use the same async context manager pattern as endpoints via `remote.run()`, delegating the actual startup and shutdown logic to the actual implementation.

Use context manager api for remote endpoint running

---

lahja/base.py

There were some errors in the implementation that needed cleaning up
Fixed them (need to add tests)

Cleanup @property stuff on BaseRemoteEndpoint

---

lahja/base.py

@property decorators are missing in the base class
Added them

Add missing decorators

---

lahja/asyncio/endpoint.py
lahja/base.py
tests/core/asyncio/conftest.py
tests/core/asyncio/test_asyncio_subscriptions_api.py
tests/core/asyncio/test_base_wait_connections_changed_api.py
tests/core/asyncio/test_base_wait_until_any_remote_subscriptions_changed_api.py
tests/core/asyncio/test_connect.py

1. Usage of `connect_to_endpoints_nowait` was discouraged and Trinity does not need it anymore
2. Having variadic `connect_to_endpoints` and non-variadic `connect_to_endpoint` is unnecessary as the former is a superset of the latter.
Removed both APIs.
Bonus: `_await_connect_to_endpoint` throws earlier in case of errors now

Removed connect_to_endpoint and connect_to_endpoints_nowait API

---

.circleci/config.yml
lahja/asyncio/endpoint.py
lahja/base.py
lahja/exceptions.py
lahja/tools/benchmark/backends.py
lahja/trio/__init__.py
lahja/trio/endpoint.py
lahja/trio/future.py
scripts/perf_benchmark.py
setup.py
tests/core/asyncio/test_compat_with_trio_endpoint.py
tests/core/trio/conftest.py
tests/core/trio/test_future.py
tests/core/trio/test_internal_events.py
tests/core/trio/test_server_establishes_reverse_connection.py
tests/core/trio/test_trio_endpoint_broadcast.py
tests/core/trio/test_trio_endpoint_compat_with_asyncio.py
tests/core/trio/test_trio_endpoint_connect.py
tests/core/trio/test_trio_endpoint_request_response.py
tests/core/trio/test_trio_endpoint_running.py
tests/core/trio/test_trio_endpoint_stream.py
tests/core/trio/test_trio_endpoint_subscribe.py
tests/core/trio/test_trio_endpoint_wait_for.py
tox.ini

replaces #56
built on #133 #135 #136
We need a trio based endpoint implementation.
Wrote an implementation using the `trio` library.

Trio base endpoint implementation

---

lahja/asyncio/endpoint.py

When you cancel an `asyncio` task you are supposed to await it to give it a chance to have the cancellation error thrown into it and for it to cleanup.  We were not doing this.
Added a `try/except` to each place we do this type of cancellation with the proper `await` statement.

Proper cancellation of asyncio tasks

---

docs/_static/css/custom.css
docs/conf.py
newsfragments/152.doc.rst

1. Lots of grey boxes make API docs harder to parse (visually)
2. Methods and attributes not being grouped makes it even harder and error prone for the reader ("Do I call this with or without parenthesis?")
Visuals today:
1. Removed grey boxes
2. Improved fonts and spacing
3. Grouped methods and attributes
Visuals after this PR:

Improve visuals of API docs

---

.project-template/template_vars.txt
LICENSE
docs/conf.py
newsfragments/150.doc.rst

1. Title in docs is wrong
2. License info was wrong
1. Refilled template vars
2. Manually adjusted some places to adjust copyright etc.

Fix wrong title in docs and license

---

docs/conf.py
newsfragments/155.doc.rst

Turns out readthedocs build is broken because the latex generation broke
Re-add some missing info that latex needs.

Fix broken Latex generation

---

lahja/asyncio/endpoint.py
lahja/base.py
lahja/trio/endpoint.py
newsfragments/156.feature.rst
newsfragments/160.feature.rst
newsfragments/feature.156.rst
tests/core/asyncio/test_basics.py

On Python < 3.8 (which isn't released yet) pickle still uses version `3` of the protocol by default (even though version `4` is already available. Python 3.8 will make version `5` the default protocol.
Always use the highest available pickle protocol.

Use the highest available pickle protocol

---

newsfragments/163.misc.rst
setup.py

Newer versions of trio are available.  We want 0.13 since it fixes a bunch of deprecation warnings.
Updated to `trio>=0.13,<0.14`

Update to trio 0.13

---

lahja/trio/endpoint.py
newsfragments/170.bugfix.rst

In trinity with the new (in progress, trio-based) peer discovery
protocol, sometimes other endpoints were trying to connect too soon,
before the IPC socket file was bound, causing an error
Also, multiple other endpoints will usually try to connect
simultaneously, causing an error as TrioEndpoint's IPC socket was
hard-coded to accept only one pending connection.
- allow more than one pending incoming connection, and use a class
attribute to configure that instead of hard-coding
- wait for the socket to be bound in _start_serving() so that others
don't try to connect too soon.

A couple fixes to TrioEndpoint

---

docs/_static/js/matomo.js
docs/conf.py
newsfragments/171.doc.rst

Currently we do not have a good insight into our target group. In order to improve both Trinity itself and the documentation, it makes sense to aggregate some data.
Add Matomo Tracking to Docs site.
Matomo is an Open Source web analytics platform that allows us
to get better insights and optimize for our audience without
the negative consequences of other compareable platforms.
Read more: https://matomo.org/why-matomo/

Add Matomo tracking

---

lahja/asyncio/endpoint.py
lahja/base.py
lahja/common.py
lahja/exceptions.py
lahja/trio/endpoint.py
newsfragments/176.feature.rst
tests/core/asyncio/test_asyncio_subscriptions_api.py
tests/core/asyncio/test_basics.py
tests/core/common/test_endpoint_broadcast.py
tests/core/common/test_endpoint_request_response.py
tests/core/trio/test_trio_endpoint_subscribe.py

It is easy to end up in a scenario where important events are forgotten to get subscribed to. This can lead to fatal bugs such as [Trinity not propagating any transactions to its peers](https://github.com/ethereum/trinity/pull/1649)
1. By default any broadcasted event as well as any send request will throw a `NoSubscriber` exception if there are no subscribers to said event/request at the time when the event/request is being made.
2. Events/Requests can still be fired if there are no subscribers but it needs to be made explicit via `BroadcastConfig(raise_if_no_subscribers=False)`. As an example, this can be useful for events that are meant for extensibility to be subscribed to conditionally based on the fact whether a specific plugin is installed or not.
I thought about using the …

Raise error if broadcast/request has no subscribers
